name: Android CI (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
  platforms;android-35
  build-tools;35.0.0

      - name: Gradle build (assembleDebug)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          arguments: ':app:assembleDebug'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
