name: Android CI (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Postavi Android SDK bez paketa
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Instaliraj pakete POSEBNO da se ne spajaju u jedan string
      - name: Install platform android-34
        run: sdkmanager "platforms;android-34"

      - name: Install build-tools 34.0.0
        run: sdkmanager "build-tools;34.0.0"

      # (opcionalno, ali korisno) Prihvati licence
      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Gradle build (assembleDebug)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          arguments: ':app:assembleDebug'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
